Vagrant.configure("2") do |config|
	config.vm.define :master01 do |node|
		node.vm.box = "precise64"
		node.vm.network :private_network, ip: "10.10.10.2", netmask: "255.255.255.0"
		node.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", 512, "--cpus", 1, "--name", "master"]
		end
	end
	config.vm.define :node01 do |node|
		node.vm.box = "precise64"
		node.vm.network :private_network, ip: "10.10.10.3", netmask: "255.255.255.0"
		node.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", 512, "--cpus", 1, "--name", "node01"]
		end
	end
	config.vm.define :master02 do |node|
		node.vm.box = "precise64"
		node.vm.network :private_network, ip: "10.10.11.2", netmask: "255.255.255.0"
		node.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", 512, "--cpus", 1, "--name", "master"]
		end
	end
	config.vm.define :node02 do |node|
		node.vm.box = "precise64"
		node.vm.network :private_network, ip: "10.10.11.3", netmask: "255.255.255.0"
		node.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", 512, "--cpus", 1, "--name", "node01"]
		end
	end
end
