Vagrant.configure("2") do |config|
	config.vm.define :master do |node|
		node.vm.box = "centos6.4"
		node.vm.hostname = "master"
		node.vm.network :private_network, ip: "10.10.10.2", netmask: "255.255.255.0"
		node.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", 512, "--cpus", 1, "--name", "master"]
		end
	end
	config.vm.define :node01 do |node|
		node.vm.box = "centos6.4"
		node.vm.hostname = "client"
		node.vm.network :private_network, ip: "10.10.10.3", netmask: "255.255.255.0"
		node.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", 512, "--cpus", 1, "--name", "node01"]
		end
	end
	config.vm.define :node02 do |node|
		node.vm.box = "centos6.4"
		node.vm.hostname = "client"
		node.vm.network :private_network, ip: "10.10.10.4", netmask: "255.255.255.0"
		node.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", 512, "--cpus", 1, "--name", "node02"]
		end
	end
end
